version: "3.8"

networks:
  freight-net:
    driver: bridge

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres-init:/docker-entrypoint-initdb.d:ro
    networks: [freight-net]
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: [freight-net]

  scheduling-api:
    build:
      context: .
      dockerfile: src/Services/Scheduling/Scheduling.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    environment:
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=scheduling_db;Username=postgres;Password=postgres
      Jwt__Issuer: freight-platform
      Jwt__Audience: freight-clients
      Jwt__Key: your-very-strong-development-secret-change-me
      Jwt__AccessTokenMinutes: 60
    depends_on: [rabbitmq, postgres]
    networks: [freight-net]

  booking-api:
    build:
      context: .
      dockerfile: src/Services/Booking/Booking.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    environment:
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=booking_db;Username=postgres;Password=postgres
      Jwt__Issuer: freight-platform
      Jwt__Audience: freight-clients
      Jwt__Key: your-very-strong-development-secret-change-me
      Jwt__AccessTokenMinutes: 60
    depends_on: [rabbitmq, postgres]
    networks: [freight-net]

  payment-api:
    build:
      context: .
      dockerfile: src/Services/Payment/Payment.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    depends_on: [rabbitmq]
    networks: [freight-net]

  invoice-api:
    build:
      context: .
      dockerfile: src/Services/Invoice/Invoice.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    depends_on: [rabbitmq]
    networks: [freight-net]

  api-gateway:
    build:
      context: .
      dockerfile: src/Gateway/ApiGateway/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - scheduling-api
      - booking-api
      - payment-api
      - invoice-api
    ports:
      - "8080:8080"
    networks: [freight-net]
